server:
  port: 18087
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.14.111:8848
    sentinel:
      transport:
        dashboard: 192.168.14.111:8080
        port: 8719
  redis:
    host: 192.168.14.111
    port: 6379
  zipkin:
    base-url: http://192.168.14.111:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  thymeleaf:
    cache: false
feign:
  sentinel:
    enabled: true
