server:
  port: 18086
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.14.111:8848
    sentinel:
      transport:
        dashboard: 192.168.14.111:8080
        port: 8719
  zipkin:
    base-url: http://192.168.14.111:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  elasticsearch:
    rest:
      uris: http://192.168.14.111:9200
  rabbitmq:
    host: 192.168.14.111
    port: 5672
    virtual-host: /mch
    username: mch
    password: 123456
    listener:
      type: simple
      simple:
        acknowledge-mode: manual
        prefetch: 1
        concurrency: 3
feign:
  sentinel:
    enabled: true
logging:
  level:
    com.atguigu.gmall: debug