server:
  port: 18083
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.14.111:8848
    sentinel:
      transport:
        dashboard: 192.168.14.111:8080
        port: 8719
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.14.111:3306/guli_sms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  redis:
    host: 192.168.14.111
    port: 6379
  zipkin:
    base-url: http://192.168.14.111:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.atguigu.gmall.sms.entity
  global-config:
    db-config:
      id-type: auto
feign:
  sentinel:
    enabled: true
seata:
  tx-service-group: gmall-tx-group
  service:
    vgroup-mapping:
      gmall-tx-group: default
    grouplist:
      default: 192.168.14.111:8091
