spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.14.111:8848
    sentinel:
      transport:
        dashboard: 192.168.14.111:8080
        port: 8719
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.14.111:3306/guli_payment?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  redis:
    host: 192.168.14.111
    port: 6379
  zipkin:
    base-url: http://192.168.14.111:9411
    discovery-client-enabled: false
    sender:
      type: web
  rabbitmq:
    host: 192.168.14.111
    port: 5672
    virtual-host: /mch
    username: mch
    password: 123456
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1
        concurrency: 6
  sleuth:
    sampler:
      probability: 1
  thymeleaf:
    cache: false
feign:
  sentinel:
    enabled: true
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
