
server:
  port: 18088
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.14.111:8848
    sentinel:
      transport:
        dashboard: 192.168.14.111:8080
        port: 8719
  zipkin:
    base-url: http://192.168.14.111:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  redis:
    host: 192.168.14.111
  thymeleaf:
    cache: false
feign:
  sentinel:
    enabled: true
logging:
  level:
    com.atguigu.gmall: debug
threadPool:
  corePoolSize: 100
  maximumPoolSize: 200
  keepAliveTime: 60
  blockingQueueSize: 5000